language: node_js
node_js:
- 0.8
env:
  global:
  - secure: gJrY9xlzy9zx7d68dKSaFG6MHZLRTS1TgMScE7iJ9SYbC8q9+2f0DJi5SXY8hH1CqEb7IFCk+vNPBFH5I/+VB+Z2K6+6ZbDHqDP1iA9YrWUwhuySE6416oyUt0VIPyLp0kVmwU+OfWsGxkOh0pFo3O+C0Fn+WNdCAR/S5liXErc=
  - secure: Sjfvs+tv0GFS1bfHtZOzQeTEepoLPvX3Vf/d3n4U8b4rBBGmyF0lphsxGQjYHuXwoU9uSbk2Gkk1G9qqaWeHTSezi6Zbm5C7h1uJFxQ5SYTBjqSB7i4eiNhpnOSZSqULl/kItO7kJ+tuOX0jA6/MBdSIe/0tsjezSQED73hhwJc=
before_script:
- npm install --silent --quiet -g yo grunt-cli bower generator-travis-ci
- bower install
script:
- grunt build
after_success:
- git submodule add -f -b master https://${GH_OAUTH_TOKEN}@github.com/TwoGuysInDesign/twoguysindesign.github.com site
- cd site
- git rm -rf .
- cp -R ../dist/* .
- cp ../dist/.* .
- git add -f .
- git config user.email "acetrike@yahoo.com"
- git config user.name "ctoestreich"
- git commit -am "adding the build files to website"
- git push https://${GH_OAUTH_TOKEN}@github.com/TwoGuysInDesign/twoguysindesign.github.com
  HEAD:master
