language: node_js
node_js:
- 0.8
env:
  global:
    - secure: DI0pBPyBCZVojCj2B76qgkrHSmEPkc1NDjHzsoyTSCokWMzgpCM7buvTTDDhy6cIm3Oofb59Tb7r1KfKjEIC5Y3ZaNJZu47yglwPaq45yURg08ekgLUcmCXd688obf4u5y5uxHImGNmrw/3HqdNcZZFIjLPA/99s1Zd6JDYEodg=
    - secure: HA8rdzIRga5eRhbc0HqE+FCuWIuXDYUItDu60izRyRsZzSIeDHVjIuLiP2trLyb0TyK167kJH37RjRsPG37sQ/HsvNjQBOu2RfsYwnUw0kj3hMenb+5YwZMTvbqme/zyDsnIjTPFVBdKD8DSj/lYJtzHlayklaeysTFD48/PZ2M=
before_script:
- npm install --silent --quiet -g yo grunt-cli bower generator-travis-ci
- bower install
script:
- grunt build
after_success:
- git submodule add -f -b master https://${GH_OAUTH_TOKEN}@github.com/TwoGuysInDesign/twoguysindesign.github.com site
- cd site
- git rm -rf .
- cp -R ../dist/* .
- cp ../dist/.* .
- git add -f .
- git config user.email "acetrike@yahoo.com"
- git config user.name "ctoestreich"
- git commit -am "adding the build files to website"
- git push https://${GH_OAUTH_TOKEN}@github.com/TwoGuysInDesign/twoguysindesign.github.com
  HEAD:master
